Add quote semantic search demo
aerospike/proximus-examples pull request #10
Opened 2024-02-27 23:37 UTC by jdogmcsteezy

I did not update the global README since that is meant to funnel people to the prism image search demo

2024-03-01 19:03 UTC, hev requested changes

2024-03-01 19:03 UTC, hev commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        <h1 class="title">Proximus Image search</h1>
```suggestion
        <h1 class="title">Proximus Semantic Text search</h1>
```

2024-03-01 19:03 UTC, hev commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        This demo application provides semantic search for a set of images
Need to update this description.

2024-03-05 23:50 UTC, hev approved these changes

2024-03-05 23:50 UTC, hev commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        by indexing them using the <a class="link-dark" href="https://huggingface.co/sentence-transformers/clip-ViT-B-32-multilingual-v1">CLIP</a>
Model still referenced as CLIP here.

2024-03-05 23:50 UTC, jdogmcsteezy commented on prism-image-search/prism/routes.py
> +        return "No test uploaded", 400
```suggestion
        return "No text uploaded", 400
```

2024-03-05 23:51 UTC, hev requested changes

2024-03-05 23:51 UTC, hev commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        by indexing them using the <a class="link-dark" href="https://huggingface.co/sentence-transformers/clip-ViT-B-32-multilingual-v1">CLIP</a>
Meant to request changes here.

2024-03-06 00:01 UTC, jdogmcsteezy commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        from each quote and stores them as vector embeddings in Aerospike. When a user
```suggestion
        by indexing them using the <a class="link-dark" href="https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2">MiniLM</a>
        model. This model generates vectors with semantic meaning 
        from each quote and stores them as vector embeddings in Aerospike. When a user
```

2024-03-06 00:06 UTC, hev requested changes

2024-03-06 00:06 UTC, hev commented on quote-semantic-search/quote-search/static/components/home.vue.js
> +        This demo application provides semantic search for a set of quotes
I think we may also want to link where the quotes came from.

2024-03-06 13:40 UTC, hev approved these changes

2024-03-06 13:44 UTC, merged