Add is-lb config param
aerospike/proximus-examples pull request #22
Opened 2024-03-28 14:40 UTC by davi17g

2024-04-01 16:25 UTC, jdogmcsteezy requested changes

2024-04-01 16:25 UTC, jdogmcsteezy commented on basic-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
Should we wait until 0.3.2 is released to merge this PR?

2024-04-01 16:26 UTC, hev requested changes

2024-04-01 16:26 UTC, hev commented on quote-semantic-search/quote-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
Overall this seems good but we need to wait for 0.4.0 to be available before we merge this into main.

2024-04-12 01:13 UTC, arrowplum commented
Can we merge this now?

2024-04-12 01:14 UTC, arrowplum commented
https://pypi.org/project/aerospike-vector/0.4.0/

2024-04-12 01:15 UTC, arrowplum commented on basic-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
```suggestion
aerospike-proximus==0.4.0
```

2024-04-12 01:16 UTC, arrowplum commented on prism-image-search/prism/requirements.txt
> +aerospike-proximus==0.3.2.dev1
```suggestion
aerospike-proximus==0.4.0
```

2024-04-12 01:17 UTC, arrowplum commented on quote-semantic-search/quote-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
```suggestion
aerospike-proximus==0.4.0
```

2024-04-12 01:18 UTC, arrowplum commented
We need to update the readmes config section

2024-04-15 20:26 UTC, jdogmcsteezy commented
I have merged this branch into my dev branch VEC-132-0.4.0. I will open a new PR soon

2024-04-15 20:26 UTC, closed without merging